name: SonarQube
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |  
              REPO_ABS_PATH=$(pwd)
      
              ALL_SOURCES=$(
                {
                  find . -type d -path "*/src/main/java"      ! -path "*/target/*" ! -path "*/.git/*" ! -path "*/.scannerwork/*"
                  find . -type d -path "*/src/main/resources" ! -path "*/target/*" ! -path "*/.git/*" ! -path "*/.scannerwork/*"
                  find . -type d -path "*/src/main/webapp"    ! -path "*/target/*" ! -path "*/.git/*" ! -path "*/.scannerwork/*"
                  find . -type d -name "src"                  ! -path "*/target/*" ! -path "*/.git/*" ! -path "*/.scannerwork/*"
                  find . -type d -name "src_wsproc"           ! -path "*/target/*" ! -path "*/.git/*" ! -path "*/.scannerwork/*"
                  find . -type d -name "src_dataClasses"      ! -path "*/target/*" ! -path "*/.git/*" ! -path "*/.scannerwork/*"
                } | xargs -I{} realpath "{}" | sort -u | tr '\n' ',' | sed 's/,$//'
              )
              [ -z "$ALL_SOURCES" ] && ALL_SOURCES="$REPO_ABS_PATH"
      
              ALL_BINARIES=$(
                find . -type d -name "classes" -path "*/target/classes" | xargs -I{} realpath "{}" | sort | tr '\n' ',' | sed 's/,$//'
              )
              [ -z "$ALL_BINARIES" ] && ALL_BINARIES="$REPO_ABS_PATH"
      
              echo ">>> Sources (abs) : $ALL_SOURCES"
              echo ">>> Binaries (abs): $ALL_BINARIES"
      
              mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                -Dsonar.projectKey=axonivy-market_a-trust-connector \
                -Dsonar.organization=axonivy-market \
                -Dsonar.scm.disabled=true \
                -Dsonar.sources="$ALL_SOURCES" \
                -Dsonar.java.binaries="$ALL_BINARIES" \
                -Dsonar.exclusions="**/target/**,**/.git/**,**/.scannerwork/**"
